### ISSUE TITLE
Reference Papers and Parameters explanations

### ISSUE THREAD

**Issue by mohanen** [TingmanYan/FDR#1]
Hi,

I'm interested in understanding your work.

Can you provide some references to the papers that it is implemented from?

It would be nice to have some explanation of the parameters in the parameters file.

**Comment by TingmanYan** [comment]
Yeah, I am glad to, but the paper is still under review. 
The review will be finished in a few weeks. Please wait for sometimes if you like.

**Comment by edgar-explorer** [comment]
@TingmanYan  Thank you for your good work, and I am very interested in your   paper. When your paper is accepted, please update your work. Good luck for you. Thank you.

**Comment by luomomo** [comment]
> Yeah, I am glad to, but the paper is still under review.
> The review will be finished in a few weeks. Please wait for sometimes if you like.

Thanks for your work. I can see in the paper it performs good. So I want to test in my picture.Do you have any experience about using your algorithm with other data set because I see you have special operation with KITTI and Middv3 ?I want to test your refinement method with my own picture, but the graph cuts part always crash in memory ( new and delete)

**Comment by TingmanYan** [comment]
What's the resolution of your image and the memory of your computer? Since the graph cuts operates on superpixels, the memory shall be enough.
The KITTI and Middv3 modes are mainly for benchmarks. You can also directly invoke the method as:
```
        FastDR fdr(im0, disp_WTA, params, maxdisp, 0);
        cv::Mat labeling, refined_disp;
        fdr.run(labeling, refined_disp);
```
where _im0_ is the color reference image and  _disp_WTA_ is the WTA disparity map. Make sure the maximum disparity of _disp_WTA_ is less than _maxdisp_.

**Comment by danielcranston** [comment]
@luomomo make sure the disparity maps you're using contain positive disparities and that your calib.txt reflect your images (heigh/width/ndisp).
